web/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from home.views import HomeView


urlpatterns = [ # pylint: disable=C0103
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('polls/', include('polls.urls')),
    path('poker_games/', include('poker_games.urls')),
]


if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/polls/urls.py
"""
Poll app URL Configuration

The `urlpatterns` list routes URLs to views which will be included in the main
urls file.
"""
from django.urls import path

from polls.views import (
    TaskCreateView, TaskListView, TaskDetailView, VoteCreateView,
    TaskDeleteView
)


urlpatterns = [ # pylint: disable=C0103
    path('task/create', TaskCreateView.as_view(), name='task-create'),
    path('task/list', TaskListView.as_view(), name='task-list'),
    path('task/<int:pk>', TaskDetailView.as_view(), name='task-detail'),
    path('task/delete/<int:pk>', TaskDeleteView.as_view(), name='task-delete'),
    path('vote/create/<int:task_id>', VoteCreateView.as_view(), name='vote-create'),
]

web/polls/models.py
"""
Poll model module that contains the Task model which has relation Vote model.
One task has many votes, and every vote has one user.
And user can be the creator or a task too.
"""
from django.db import models

from django.contrib.auth.models import User

from poker_games.models import PokerGame


PLANNING_CARDS = (
    ('0', '0'),
    ('1/2', '1/2'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('5', '5'),
    ('8', '8'),
    ('13', '13'),
)

class Task(models.Model):
    """Task model definition."""
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    poker_game = models.ForeignKey(PokerGame, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Vote(models.Model):
    """Vote model definition."""
    value = models.CharField(
        max_length=3,
        choices=PLANNING_CARDS,
    )
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.task} - {self.value} - {self.user}'

web/polls/forms.py
"""
Forms module contains the TaskForm and the VoteForm classes definition.
"""
from django import forms


from polls.models import Task, Vote

class TaskForm(forms.ModelForm):
    """Task form class definition."""
    class Meta: # pylint: disable=R0903,C0111
        model = Task
        fields = ['name']


    def __init__(self, *args, **kwargs):
        """
        Gets the `user` instance from the kwargs and assigns it it the `user`
        class attribue.
        """
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        """
        Gets the `user` class attribute value to assign it to the `created_by`
        `Task` model field when saving to the database.
        """
        self.instance.created_by = self.user
        return super().save()


class VoteForm(forms.ModelForm):
    """Vote form class definition."""
    class Meta: # pylint: disable=R0903,C0111
        model = Vote
        fields = ['value']
        widgets = {'value': forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        """
        Gets the `user` instance and `task_id` from the kwargs and assigns them
        as class attribue.
        """
        self.user = kwargs.pop('user')
        self.task_id = kwargs.pop('task_id')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        """
        Gets the `user` and the `task_id` class attribute value to assign it to
        the `user`, `task_id` in the `Vote` model fields when saving to the
        database.

        The `update_or_create` method was used to prevent creating object every
        time, which is the default behaviour, but update the Vote if exists.
        """
        vote, _ = Vote.objects.update_or_create( # pylint: disable=E1101
            user=self.user,
            task_id=self.task_id,
            defaults={'value': self.instance.value}
        )

        return vote

web/polls/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView

from polls.forms import TaskForm, VoteForm
from polls.models import Task, Vote


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    success_url = reverse_lazy('task-list')
    form_class = TaskForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {
                'user': self.request.user,
            }
        )
        return kwargs


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    ordering = '-created_at'


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vote_list'] = Vote.objects.filter(task_id=self.object.id)
        return context


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('task-list')


class VoteCreateView(LoginRequiredMixin, CreateView):
    model = Vote
    form_class = VoteForm

    def get_success_url(self):
        return reverse_lazy('task-detail', args=[self.kwargs['task_id']])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_id'] = context['form'].task_id
        return context


    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {
                'user': self.request.user,
                'task_id': self.kwargs['task_id']
            }
        )
        return kwargs

web/polls/templates/polls/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h2>Deleting "{{ object }}"</h2>
  </div>
  <div class="row">
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input class="btn btn-primary" type="submit" value="Confirm">
    </form>
  </div>
</div>
{% endblock content %}

web/polls/templates/polls/task_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h2>Task name: {{ object.name }}</h2>
  </div>
  <div class="row">
    {% if vote_list %}
    <table class="table table-striped">
      <tr>
        <th>User</th>
        <th>Vote</th>
        <th>Modified at</th>
        <th>Created at</th>
        <th>Modified at</th>
      </tr>
      {% for vote in vote_list %}
      <tr>
        <td>{{ vote.user }}</td>
        <td>{{ vote.value }}</td>
        <td>{{ task.modified_at }}</td>
        <td>{{ task.created_at }}</td>
        <td>{{ task.modified_at }}</td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
      <p>No votes were created yet!</p>
    {% endif %}
  </div>
</div>
{% endblock content %}

web/polls/templates/polls/task_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h1>Create Task</h1>
  </div>
  <div class="row">
    <form method="post">{% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" value="Save">
    </form>
  </div>
</div>
{% endblock content %}

web/polls/templates/polls/task_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h2>Tasks list</h2>
  </div>
  <div class="row">
  {% if object_list %}
    <table class="table table-striped">
      <tr>
        <th>Task name</th>
        <th>Created by</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
      {% for task in object_list %}
      <tr>
        <td><a href="{% url 'task-detail' task.id %}">{{ task.name }}</a></td>
        <td>{{ task.created_by }}</td>
        <td>{{ task.created_at }}</td>
        <td>
          <a href="{% url 'vote-create' task.id %}" class="btn btn-primary"><i class="fas fa-vote-yea"></i></a>
          <a href="" class="btn btn-info"><i class="far fa-edit"></i></a>
          <a href="{% url 'task-delete' task.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
        </td>
      </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No tasks were created yet!</p>
  {% endif %}
  </div>
</div>
{% endblock content %}

web/polls/templates/polls/vote_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row">
  <h1>Submit vote</h1>
</div>
<div class="row">
  <div class="col-2 offset-5">
    <form method="post">{% csrf_token %}
      {{ form.as_p }}
      <input type="image" id="card-empty" class="my-5 mb-5"src="{% static "polls/card-empty.svg" %}" width=100% alt="Submit">
    </form>
  </div>
</div>
<div id="select-message-part-1" class="row offset-4">
  <h2>Please choose your card below</h2>
</div>
<div id="select-message-part-2" class="row offset-6">
  <h2> 👇 </h2>
</div>
<div class="row my-5">
  <div class="col-1">
    <img id="card-0" src="{% static "polls/card-0.svg" %}" alt="card 0" width="100%">
  </div>
  <div class="col-1">
    <img id="card-1-2" src="{% static "polls/card-1-2.svg" %}" alt="card 1/2" width="100%">
  </div>
  <div class="col-1">
    <img id="card-1" src="{% static "polls/card-1.svg" %}" alt="card 1" width="100%">
  </div>
  <div class="col-1">
    <img id="card-2" src="{% static "polls/card-2.svg" %}" alt="card 2" width="100%">
  </div>
  <div class="col-1">
    <img id="card-3" src="{% static "polls/card-3.svg" %}" alt="card 3" width="100%">
  </div>
  <div class="col-1">
    <img id="card-5" src="{% static "polls/card-5.svg" %}" alt="card 5" width="100%">
  </div>
  <div class="col-1">
    <img id="card-8" src="{% static "polls/card-8.svg" %}" alt="card 8" width="100%">
  </div>
  <div class="col-1">
    <img id="card-13" src="{% static "polls/card-13.svg" %}" alt="card 13" width="100%">
  </div>
  <div class="col-1">
    <img id="card-20" src="{% static "polls/card-20.svg" %}" alt="card 20" width="100%">
  </div>
  <div class="col-1">
    <img id="card-40" src="{% static "polls/card-40.svg" %}" alt="card 40" width="100%">
  </div>
  <div class="col-1">
    <img id="card-100" src="{% static "polls/card-100.svg" %}" alt="card 10" width="100%">
  </div>
  <div class="col-1">
    <img id="card-exclamation-point" src="{% static "polls/card-exclamation-point.svg" %}" alt="card ?" width="100%">
  </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
$(document).ready(function(){
  const cardEmpty = $( "#card-empty" );
  const voteInput = $( "#id_value" );
  var voteValue;
  var lastCardSelected;
  var cards = [
    {"id": "#card-0", "value": "0"},
    {"id": "#card-1-2", "value": "1/2"},
    {"id": "#card-1", "value": "1"},
    {"id": "#card-2", "value": "2"},
    {"id": "#card-3", "value": "3"},
    {"id": "#card-5", "value": "5"},
    {"id": "#card-8", "value": "8"},
    {"id": "#card-13", "value": "13"},
    {"id": "#card-20", "value": "20"},
    {"id": "#card-40", "value": "40"},
    {"id": "#card-100", "value": "100"},
    {"id": "#card-exclamation-point", "value": "?"},
  ]

  function showConfirmMessage(value) {
    let selectMessagePart1 = $( "#select-message-part-1" );
    selectMessagePart1.removeClass("offset-4");
    selectMessagePart1.addClass("offset-6");
    selectMessagePart1.html("<h2> 👆 </h2>");
    let selectMessagePart2 = $( "#select-message-part-2" );
    selectMessagePart2.removeClass("offset-6");
    selectMessagePart2.addClass("offset-2");
    selectMessagePart2.html("<h2>Please click on the card above to confirm your choice</h2>");

  }

  function selectCard(event){
    let currentCardSelector = $( this )
    currentCardSelector.prop('disabled',true).css('opacity',0.5);
      if (lastCardSelected != undefined) {
        $( lastCardSelected ).prop('disabled',false).css('opacity',1);
      }
      lastCardSelected = this;
      cardEmpty.attr("src", currentCardSelector.attr("src"));
      showConfirmMessage();
      voteValue = event.data.value;
  }

  function setVoteValue(){
    voteInput.attr("value", voteValue);
  }
  cardEmpty.on("click", setVoteValue);


  for (let i=0; i < cards.length; i++){
    console.log(cards[i]["id"]);
    $( cards[i]["id"] ).on("click", {value: cards[i]["value"]}, selectCard);
  }
});
</script>
{% endblock extra_js %}