web/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from home.views import HomeView


urlpatterns = [ # pylint: disable=C0103
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('polls/', include('polls.urls')),
    path('poker_games/', include('poker_games.urls')),
]


if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/poker_games/urls.py
"""
Poll app URL Configuration

The `urlpatterns` list routes URLs to views which will be included in the main
urls file.
"""
from django.urls import path

from poker_games.views import (
    PokerGameCreateView, PokerGameListView, PokerGameDetailView,
    PokerGameDeleteView
)


urlpatterns = [ # pylint: disable=C0103
    path('poker-game/create', PokerGameCreateView.as_view(), name='poker-game-create'),
    path('poker-game/list', PokerGameListView.as_view(), name='poker-game-list'),
    path('poker-game/<int:pk>', PokerGameDetailView.as_view(), name='poker-game-detail'),
    path('poker-game/delete/<int:pk>', PokerGameDeleteView.as_view(), name='poker-game-delete'),
]

web/polls/urls.py
"""
Poll app URL Configuration

The `urlpatterns` list routes URLs to views which will be included in the main
urls file.
"""
from django.urls import path

from polls.views import (
    TaskCreateView, TaskListView, TaskDetailView, VoteCreateView,
    TaskDeleteView
)


urlpatterns = [ # pylint: disable=C0103
    path('task/create', TaskCreateView.as_view(), name='task-create'),
    path('task/list', TaskListView.as_view(), name='task-list'),
    path('task/<int:pk>', TaskDetailView.as_view(), name='task-detail'),
    path('task/delete/<int:pk>', TaskDeleteView.as_view(), name='task-delete'),
    path('vote/create/<int:task_id>', VoteCreateView.as_view(), name='vote-create'),
]

web/poker_games/models.py
from django.db import models
from django.contrib.auth.models import User


class PokerGame(models.Model):
    """PokerGame model definition."""

    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

web/polls/models.py
"""
Poll model module that contains the Task model which has relation Vote model.
One task has many votes, and every vote has one user.
And user can be the creator or a task too.
"""
from django.db import models

from django.contrib.auth.models import User

from poker_games.models import PokerGame


PLANNING_CARDS = (
    ('0', '0'),
    ('1/2', '1/2'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('5', '5'),
    ('8', '8'),
    ('13', '13'),
)

class Task(models.Model):
    """Task model definition."""
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    poker_game = models.ForeignKey(PokerGame, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Vote(models.Model):
    """Vote model definition."""
    value = models.CharField(
        max_length=3,
        choices=PLANNING_CARDS,
    )
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.task} - {self.value} - {self.user}'

web/poker_games/forms.py
"""Forms module contains the PokerGameForm and the class definition."""
from django import forms

from poker_games.models import PokerGame


class PokerGameForm(forms.ModelForm):
    """PokerGame form class definition."""

    class Meta: # pylint: disable=R0903,C0111
        model = PokerGame
        fields = ['name']


    def __init__(self, *args, **kwargs):
        """
        Gets the `user` instance from the kwargs and assigns it it the `user`
        class attribue.
        """
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        """
        Gets the `user` class attribute value to assign it to the `created_by`
        `PokerGame` model field when saving to the database.
        """
        self.instance.created_by = self.user
        return super().save()

web/poker_games/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView

from polls.models import Task
from poker_games.forms import PokerGameForm
from poker_games.models import PokerGame


class PokerGameCreateView(LoginRequiredMixin, CreateView):
    model = PokerGame
    success_url = reverse_lazy('poker-game-list')
    form_class = PokerGameForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update(
            {
                'user': self.request.user,
            }
        )
        return kwargs


class PokerGameListView(LoginRequiredMixin, ListView):
    model = PokerGame
    ordering = '-created_at'


class PokerGameDetailView(LoginRequiredMixin, DetailView):
    model = PokerGame

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_list'] = Task.objects.filter(poker_game_id=self.object.id)
        return context


class PokerGameDeleteView(LoginRequiredMixin, DeleteView):
    model = PokerGame
    success_url = reverse_lazy('poker-game-list')

web/poker_games/templates/poker_games/pokergame_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h2>Deleting "{{ object }}"</h2>
  </div>
  <div class="row">
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input class="btn btn-primary" type="submit" value="Confirm">
    </form>
  </div>
</div>
{% endblock content %}

web/poker_games/templates/poker_games/pokergame_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12 text-center mb-5">
      <h2>{{ object.name }}</h2>
    </div>
  </div>
  <div class="row">
    {% if task_list %}
    <div class="col-12">
      <table class="table table-striped">
        <tr>
          <th>Task name</th>
          <th>Created by</th>
          <th>Created at</th>
          <th>Actions</th>
        </tr>
        {% for task in task_list %}
        <tr>
          <td><a href="{% url 'task-detail' task.id %}">{{ task.name }}</a></td>
          <td>{{ task.created_by }}</td>
          <td>{{ task.created_at }}</td>
          <td>
            <a href="{% url 'vote-create' task.id %}" class="btn btn-primary"><i class="fas fa-vote-yea"></i></a>
            <a href="" class="btn btn-info"><i class="far fa-edit"></i></a>
            <a href="{% url 'task-delete' task.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
          </td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
        <p>No Tasks were added yet!</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

web/poker_games/templates/poker_games/pokergame_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <h1>Create Poker Game</h1>
  </div>
  <div class="row">
    <form method="post">{% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" value="Save">
    </form>
  </div>
</div>
{% endblock content %}

web/poker_games/templates/poker_games/pokergame_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row my-5">
    <div class="col-11">
      <h2>Planning Poker Games</h2>
    </div>
    <div class="col-1">
      <a href="{% url 'poker-game-create' %}" class="btn btn-success"><i class="fas fa-plus-circle"></i></a>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      {% if object_list %}
        <table class="table table-striped">
          <tr>
            <th>Poker Game name</th>
            <th>Number of tasks</th>
            <th>Created by</th>
            <th>Created at</th>
            <th>Actions</th>
          </tr>
          {% for poker_game in object_list %}
          <tr>
            <td><a href="{% url 'poker-game-detail' poker_game.id %}">{{ poker_game.name }}</a></td>
            <td>{{ poker_game.task_set.count }}</td>
            <td>{{ poker_game.created_by }}</td>
            <td>{{ poker_game.created_at }}</td>
            <td>
              <a href="" class="btn btn-info"><i class="far fa-edit"></i></a>
              <a href="{% url 'poker-game-delete' poker_game.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i></a>
            </td>
          </tr>
          {% endfor %}
        </table>
      {% else %}
        <p>No poker_games were created yet!</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}